# ============================================================================
# Cloud Build Configuration - AVD UISA
# ============================================================================
#
# Este arquivo configura o CI/CD automático no Google Cloud Build
# 
# Trigger automático:
# - Push para branch main → Deploy em produção
# - Push para branch staging → Deploy em staging
# - Pull Request → Build e testes apenas
#
# ============================================================================

# Opções globais
options:
  # Usar máquina mais potente para builds mais rápidos
  machineType: 'E2_HIGHCPU_8'
  
  # Aumentar timeout (build pode levar 10-15 min)
  timeout: '1800s'  # 30 minutos
  
  # Logging
  logging: CLOUD_LOGGING_ONLY
  
  # Usar Docker BuildKit para cache eficiente
  env:
    - 'DOCKER_BUILDKIT=1'

# Substituições (variáveis configuráveis)
substitutions:
  _PROJECT_ID: 'seu-project-id'
  _REGION: 'southamerica-east1'
  _SERVICE_NAME: 'avd-uisa'
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}'
  _CLOUD_SQL_INSTANCE: '${_PROJECT_ID}:${_REGION}:avd-uisa-db'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '10'
  _MEMORY: '2Gi'
  _CPU: '2'
  _TIMEOUT: '300'
  _CONCURRENCY: '80'

# Steps do pipeline
steps:
  # ============================================================================
  # STEP 1: Verificar Node.js e dependências
  # ============================================================================
  - name: 'node:20-alpine'
    id: 'validate-dependencies'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🔍 Validando package.json e dependências..."
        npm install -g pnpm@10.15.1
        pnpm --version
        echo "✅ Node.js e pnpm configurados"

  # ============================================================================
  # STEP 2: Executar testes (opcional - descomente se tiver testes)
  # ============================================================================
  # - name: 'node:20-alpine'
  #   id: 'run-tests'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       echo "🧪 Executando testes..."
  #       npm install -g pnpm@10.15.1
  #       pnpm install --frozen-lockfile
  #       pnpm test
  #       echo "✅ Testes passaram"

  # ============================================================================
  # STEP 3: Build da imagem Docker
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--cache-from'
      - '${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '-t'
      - '${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '-t'
      - '${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA'
      - '.'
    timeout: '1200s'  # 20 minutos para build

  # ============================================================================
  # STEP 4: Push da imagem para Container Registry
  # ============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_IMAGE_NAME}'

  # ============================================================================
  # STEP 5: Deploy no Cloud Run (apenas em main/staging)
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Verificar branch
        if [[ "$BRANCH_NAME" == "main" ]]; then
          ENV="production"
          SERVICE_NAME="${_SERVICE_NAME}"
          MIN_INSTANCES="${_MIN_INSTANCES}"
        elif [[ "$BRANCH_NAME" == "staging" ]]; then
          ENV="staging"
          SERVICE_NAME="${_SERVICE_NAME}-staging"
          MIN_INSTANCES="0"
        else
          echo "⏭️  Pulando deploy (branch não é main ou staging)"
          exit 0
        fi

        echo "🚀 Deploying to $ENV environment..."

        gcloud run deploy $SERVICE_NAME \
          --image ${_IMAGE_NAME}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "NODE_ENV=$ENV" \
          --add-cloudsql-instances ${_CLOUD_SQL_INSTANCE} \
          --min-instances $MIN_INSTANCES \
          --max-instances ${_MAX_INSTANCES} \
          --memory ${_MEMORY} \
          --cpu ${_CPU} \
          --timeout ${_TIMEOUT} \
          --concurrency ${_CONCURRENCY} \
          --port 3000 \
          --ingress all \
          --service-account avd-uisa-sa@${_PROJECT_ID}.iam.gserviceaccount.com \
          --vpc-connector avd-connector \
          --vpc-egress private-ranges-only \
          --labels "env=$ENV,app=avd-uisa,managed-by=cloud-build" \
          --quiet

        # Obter URL do serviço
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME \
          --region ${_REGION} \
          --format 'value(status.url)')

        echo "✅ Deploy concluído!"
        echo "🌐 URL: $SERVICE_URL"

        # Testar health check
        echo "🔍 Testando health check..."
        sleep 10
        curl -f $SERVICE_URL/health || echo "⚠️  Health check falhou"

  # ============================================================================
  # STEP 6: Executar migrações do banco de dados (se necessário)
  # ============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "staging" ]]; then
          echo "⏭️  Pulando migrations (branch não é main ou staging)"
          exit 0
        fi

        echo "🗄️  Executando migrations..."
        
        # Executar migrations via Cloud Run job ou Cloud SQL Proxy
        # Exemplo: usar Cloud Run job para rodar migrations
        # gcloud run jobs execute avd-uisa-migrations \
        #   --region ${_REGION} \
        #   --wait

        echo "✅ Migrations concluídas"

  # ============================================================================
  # STEP 7: Notificar Slack/Email sobre deploy (opcional)
  # ============================================================================
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'notify-deploy'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       if [[ "$BRANCH_NAME" == "main" ]]; then
  #         SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
  #           --region ${_REGION} \
  #           --format 'value(status.url)')
  #         
  #         curl -X POST https://hooks.slack.com/services/YOUR/WEBHOOK/URL \
  #           -H 'Content-Type: application/json' \
  #           -d "{\"text\":\"✅ AVD UISA deployed to production: $SERVICE_URL\"}"
  #       fi

# ============================================================================
# Artifacts: Armazenar logs e relatórios
# ============================================================================
artifacts:
  objects:
    location: 'gs://${_PROJECT_ID}_cloudbuild/logs'
    paths:
      - 'build.log'

# ============================================================================
# Images: Especificar imagens a serem armazenadas
# ============================================================================
images:
  - '${_IMAGE_NAME}:$COMMIT_SHA'
  - '${_IMAGE_NAME}:latest'
  - '${_IMAGE_NAME}:$BRANCH_NAME-$SHORT_SHA'

# ============================================================================
# Logs: Configuração de logging
# ============================================================================
logsBucket: 'gs://${_PROJECT_ID}_cloudbuild'

# ============================================================================
# Configuração do Trigger (criar via console ou gcloud):
# ============================================================================
#
# gcloud builds triggers create github \
#   --name="avd-uisa-main-deploy" \
#   --repo-name="avd-uisa-sistema-completo" \
#   --repo-owner="rrodrigogon-byte" \
#   --branch-pattern="^main$" \
#   --build-config="cloudbuild.yaml" \
#   --substitutions='_PROJECT_ID=seu-project-id,_REGION=southamerica-east1'
#
# ============================================================================
# Variáveis de Ambiente (configurar no Secret Manager):
# ============================================================================
#
# 1. Criar secrets:
# gcloud secrets create DATABASE_URL --data-file=-
# gcloud secrets create JWT_SECRET --data-file=-
# gcloud secrets create SMTP_PASS --data-file=-
#
# 2. Conceder acesso ao Cloud Run:
# gcloud secrets add-iam-policy-binding DATABASE_URL \
#   --member="serviceAccount:avd-uisa-sa@PROJECT_ID.iam.gserviceaccount.com" \
#   --role="roles/secretmanager.secretAccessor"
#
# 3. Atualizar Cloud Run service:
# gcloud run services update avd-uisa \
#   --update-secrets=DATABASE_URL=DATABASE_URL:latest \
#   --update-secrets=JWT_SECRET=JWT_SECRET:latest \
#   --update-secrets=SMTP_PASS=SMTP_PASS:latest
#
# ============================================================================
