-- Adicionar novos campos à tabela employees

-- Verificar e adicionar campo personalEmail
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS personalEmail VARCHAR(320),
ADD COLUMN IF NOT EXISTS corporateEmail VARCHAR(320),
ADD COLUMN IF NOT EXISTS chapa VARCHAR(50),
ADD COLUMN IF NOT EXISTS codSecao VARCHAR(100),
ADD COLUMN IF NOT EXISTS secao VARCHAR(255),
ADD COLUMN IF NOT EXISTS codFuncao VARCHAR(50),
ADD COLUMN IF NOT EXISTS funcao VARCHAR(255),
ADD COLUMN IF NOT EXISTS situacao VARCHAR(50),
ADD COLUMN IF NOT EXISTS gerencia VARCHAR(255),
ADD COLUMN IF NOT EXISTS diretoria VARCHAR(255),
ADD COLUMN IF NOT EXISTS cargo VARCHAR(255),
ADD COLUMN IF NOT EXISTS telefone VARCHAR(50);

-- Modificar campos que eram NOT NULL para permitir NULL
ALTER TABLE employees 
MODIFY COLUMN email VARCHAR(320) NULL,
MODIFY COLUMN hireDate DATETIME NULL,
MODIFY COLUMN departmentId INT NULL,
MODIFY COLUMN positionId INT NULL;
