DROP TABLE `analyticsMetrics`;--> statement-breakpoint
DROP TABLE `approvals`;--> statement-breakpoint
DROP TABLE `behavioralCompetencies`;--> statement-breakpoint
DROP TABLE `bonusCalculations`;--> statement-breakpoint
DROP TABLE `bonusEligibility`;--> statement-breakpoint
DROP TABLE `bonusPrograms`;--> statement-breakpoint
DROP TABLE `competencies`;--> statement-breakpoint
DROP TABLE `departments`;--> statement-breakpoint
DROP TABLE `developmentActions`;--> statement-breakpoint
DROP TABLE `developmentPlans`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `evaluationCycles`;--> statement-breakpoint
DROP TABLE `evaluationTemplates`;--> statement-breakpoint
DROP TABLE `evaluations`;--> statement-breakpoint
DROP TABLE `goalProgress`;--> statement-breakpoint
DROP TABLE `goals`;--> statement-breakpoint
DROP TABLE `jobDescriptionApprovalHistory`;--> statement-breakpoint
DROP TABLE `jobDescriptions`;--> statement-breakpoint
DROP TABLE `jobRequirements`;--> statement-breakpoint
DROP TABLE `jobResponsibilities`;--> statement-breakpoint
DROP TABLE `notificationLogs`;--> statement-breakpoint
DROP TABLE `notificationSettings`;--> statement-breakpoint
DROP TABLE `pendencies`;--> statement-breakpoint
DROP TABLE `pirApprovalHistory`;--> statement-breakpoint
DROP TABLE `pirGoals`;--> statement-breakpoint
DROP TABLE `pirProgress`;--> statement-breakpoint
DROP TABLE `pirs`;--> statement-breakpoint
DROP TABLE `positionHistory`;--> statement-breakpoint
DROP TABLE `readinessAssessments`;--> statement-breakpoint
DROP TABLE `reports`;--> statement-breakpoint
DROP TABLE `successionCandidates`;--> statement-breakpoint
DROP TABLE `successionPlans`;--> statement-breakpoint
DROP TABLE `systemLogs`;--> statement-breakpoint
DROP TABLE `technicalCompetencies`;--> statement-breakpoint
DROP TABLE `timeAdjustments`;--> statement-breakpoint
DROP TABLE `timeBank`;--> statement-breakpoint
DROP TABLE `timeRecords`;