CREATE TABLE `departmentGoals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`departmentId` int NOT NULL,
	`cycleId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`targetValue` int,
	`currentValue` int DEFAULT 0,
	`unit` varchar(50),
	`weight` int NOT NULL DEFAULT 10,
	`startDate` datetime,
	`dueDate` datetime,
	`status` enum('rascunho','aprovada','em_andamento','concluida','cancelada') NOT NULL DEFAULT 'rascunho',
	`progressPercent` int NOT NULL DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `departmentGoals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `evaluationWeightConfigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`scope` enum('global','departamento','cargo') NOT NULL DEFAULT 'global',
	`departmentId` int,
	`positionId` int,
	`competenciesWeight` int NOT NULL DEFAULT 40,
	`individualGoalsWeight` int NOT NULL DEFAULT 30,
	`departmentGoalsWeight` int NOT NULL DEFAULT 15,
	`pirWeight` int NOT NULL DEFAULT 15,
	`feedbackWeight` int DEFAULT 0,
	`behaviorWeight` int DEFAULT 0,
	`validFrom` datetime NOT NULL,
	`validUntil` datetime,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evaluationWeightConfigs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `evaluationWeightHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`previousWeights` json,
	`newWeights` json,
	`changeReason` text,
	`changedBy` int NOT NULL,
	`changedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `evaluationWeightHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `individualGoalProgress` (
	`id` int AUTO_INCREMENT NOT NULL,
	`goalId` int NOT NULL,
	`previousValue` int,
	`newValue` int NOT NULL,
	`previousPercent` int,
	`newPercent` int NOT NULL,
	`comment` text,
	`evidence` text,
	`recordedBy` int NOT NULL,
	`recordedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `individualGoalProgress_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `individualGoals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`departmentGoalId` int,
	`cycleId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`specific` text,
	`measurable` text,
	`achievable` text,
	`relevant` text,
	`timeBound` text,
	`targetValue` int,
	`currentValue` int DEFAULT 0,
	`unit` varchar(50),
	`weight` int NOT NULL DEFAULT 10,
	`priority` enum('baixa','media','alta','critica') NOT NULL DEFAULT 'media',
	`startDate` datetime,
	`dueDate` datetime,
	`completedAt` datetime,
	`status` enum('rascunho','pendente_aprovacao','aprovada','em_andamento','concluida','cancelada','atrasada') NOT NULL DEFAULT 'rascunho',
	`progressPercent` int NOT NULL DEFAULT 0,
	`approvedBy` int,
	`approvedAt` datetime,
	`rejectionReason` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `individualGoals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performanceAlerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`cycleId` int,
	`alertType` enum('competencia_abaixo_minimo','meta_atrasada','desempenho_geral_baixo','gap_critico','sem_avaliacao') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'warning',
	`title` varchar(255) NOT NULL,
	`description` text,
	`competencyId` int,
	`goalId` int,
	`expectedValue` int,
	`actualValue` int,
	`gapValue` int,
	`status` enum('aberto','em_analise','resolvido','ignorado') NOT NULL DEFAULT 'aberto',
	`resolvedBy` int,
	`resolvedAt` datetime,
	`resolutionNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `performanceAlerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performanceBenchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scope` enum('organizacao','departamento','cargo') NOT NULL,
	`departmentId` int,
	`positionId` int,
	`periodStart` datetime NOT NULL,
	`periodEnd` datetime NOT NULL,
	`avgCompetencyScore` int,
	`avgGoalCompletion` int,
	`avgOverallScore` int,
	`p25Score` int,
	`p50Score` int,
	`p75Score` int,
	`p90Score` int,
	`totalEmployees` int NOT NULL,
	`evaluatedEmployees` int NOT NULL,
	`abaixoExpectativas` int DEFAULT 0,
	`atendeExpectativas` int DEFAULT 0,
	`superaExpectativas` int DEFAULT 0,
	`excepcional` int DEFAULT 0,
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `performanceBenchmarks_id` PRIMARY KEY(`id`)
);
