CREATE TABLE `activityJobDescriptionMatch` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`jobDescriptionId` int NOT NULL,
	`periodStart` date NOT NULL,
	`periodEnd` date NOT NULL,
	`totalActivitiesLogged` int DEFAULT 0,
	`activitiesMatchedToJob` int DEFAULT 0,
	`activitiesNotInJob` int DEFAULT 0,
	`responsibilitiesNotExecuted` int DEFAULT 0,
	`adherencePercentage` int DEFAULT 0,
	`coveragePercentage` int DEFAULT 0,
	`matchDetails` json,
	`gapsIdentified` json,
	`suggestedAdjustments` json,
	`executiveSummary` text,
	`status` enum('processing','completed','reviewed') NOT NULL DEFAULT 'processing',
	`reviewedBy` int,
	`reviewedAt` datetime,
	`reviewComments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activityJobDescriptionMatch_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `activityRoutines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`jobDescriptionId` int,
	`responsibilityId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`frequency` enum('diaria','semanal','quinzenal','mensal','trimestral','eventual') NOT NULL,
	`estimatedMinutes` int,
	`category` enum('processo','analise','planejamento','comunicacao','reuniao','relatorio','suporte','administrativo','outros') NOT NULL,
	`isLinkedToJobDescription` boolean NOT NULL DEFAULT false,
	`matchPercentage` int DEFAULT 0,
	`matchNotes` text,
	`weekDays` json,
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activityRoutines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `departmentApprovalConfig` (
	`id` int AUTO_INCREMENT NOT NULL,
	`departmentId` int NOT NULL,
	`defaultCsSpecialistId` int,
	`defaultCsSpecialistName` varchar(255),
	`defaultHrManagerId` int,
	`defaultHrManagerName` varchar(255),
	`defaultGaiDirectorId` int,
	`defaultGaiDirectorName` varchar(255),
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `departmentApprovalConfig_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `desktopActivityLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`activityType` enum('application','website','document','meeting','email','idle','other') NOT NULL,
	`applicationName` varchar(255),
	`windowTitle` varchar(500),
	`url` varchar(1000),
	`documentPath` varchar(500),
	`startTime` datetime NOT NULL,
	`endTime` datetime,
	`durationSeconds` int,
	`autoCategory` varchar(100),
	`matchedResponsibilityId` int,
	`confidenceScore` int,
	`deviceId` varchar(100),
	`deviceType` enum('desktop','laptop','mobile') DEFAULT 'desktop',
	`processed` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `desktopActivityLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobDescriptionApprovalFlow` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobDescriptionId` int NOT NULL,
	`version` int NOT NULL DEFAULT 1,
	`status` enum('draft','pending_leader','pending_cs_specialist','pending_hr_manager','pending_gai_director','approved','rejected','returned') NOT NULL DEFAULT 'draft',
	`leaderId` int NOT NULL,
	`leaderName` varchar(255),
	`leaderStatus` enum('pending','approved','rejected','returned') NOT NULL DEFAULT 'pending',
	`leaderComments` text,
	`leaderDecidedAt` datetime,
	`csSpecialistId` int NOT NULL,
	`csSpecialistName` varchar(255),
	`csSpecialistStatus` enum('pending','approved','rejected','returned') NOT NULL DEFAULT 'pending',
	`csSpecialistComments` text,
	`csSpecialistDecidedAt` datetime,
	`hrManagerId` int NOT NULL,
	`hrManagerName` varchar(255),
	`hrManagerStatus` enum('pending','approved','rejected','returned') NOT NULL DEFAULT 'pending',
	`hrManagerComments` text,
	`hrManagerDecidedAt` datetime,
	`gaiDirectorId` int NOT NULL,
	`gaiDirectorName` varchar(255),
	`gaiDirectorStatus` enum('pending','approved','rejected','returned') NOT NULL DEFAULT 'pending',
	`gaiDirectorComments` text,
	`gaiDirectorDecidedAt` datetime,
	`submittedBy` int,
	`submittedAt` datetime,
	`completedAt` datetime,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobDescriptionApprovalFlow_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobDescriptionApprovalHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`flowId` int NOT NULL,
	`jobDescriptionId` int NOT NULL,
	`action` enum('created','submitted','approved','rejected','returned','resubmitted','cancelled') NOT NULL,
	`level` int NOT NULL,
	`levelName` varchar(100),
	`userId` int NOT NULL,
	`userName` varchar(255),
	`userRole` varchar(100),
	`comments` text,
	`previousState` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `jobDescriptionApprovalHistory_id` PRIMARY KEY(`id`)
);
