CREATE TABLE `advancedReportExports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportType` enum('movimentacoes','desempenho','hierarquia','competencias','pdi','avaliacoes','metas','bonus','customizado') NOT NULL,
	`format` enum('excel','pdf') NOT NULL,
	`filters` json,
	`chartConfig` json,
	`status` enum('pendente','processando','concluido','erro') NOT NULL DEFAULT 'pendente',
	`fileUrl` text,
	`fileSize` int,
	`errorMessage` text,
	`userId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `advancedReportExports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `permissionAccessLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userEmail` varchar(320),
	`userName` text,
	`action` varchar(200) NOT NULL,
	`resource` varchar(200) NOT NULL,
	`resourceId` int,
	`accessGranted` boolean NOT NULL,
	`denialReason` text,
	`requiredPermissions` json,
	`userPermissions` json,
	`ipAddress` varchar(45),
	`userAgent` text,
	`requestPath` text,
	`requestMethod` varchar(10),
	`metadata` json,
	`riskLevel` enum('baixo','medio','alto','critico') DEFAULT 'baixo',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `permissionAccessLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `securityMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodStart` datetime NOT NULL,
	`periodEnd` datetime NOT NULL,
	`totalAccessAttempts` int NOT NULL DEFAULT 0,
	`successfulAccesses` int NOT NULL DEFAULT 0,
	`deniedAccesses` int NOT NULL DEFAULT 0,
	`lowRiskCount` int NOT NULL DEFAULT 0,
	`mediumRiskCount` int NOT NULL DEFAULT 0,
	`highRiskCount` int NOT NULL DEFAULT 0,
	`criticalRiskCount` int NOT NULL DEFAULT 0,
	`uniqueUsers` int NOT NULL DEFAULT 0,
	`suspiciousUsers` int NOT NULL DEFAULT 0,
	`topResources` json,
	`topActions` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `securityMetrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `userNotificationSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`enableProcessStart` boolean NOT NULL DEFAULT true,
	`enableStepCompleted` boolean NOT NULL DEFAULT true,
	`enableStepReminder` boolean NOT NULL DEFAULT true,
	`enableGoalUpdate` boolean NOT NULL DEFAULT true,
	`enableEvaluationRequest` boolean NOT NULL DEFAULT true,
	`enablePdiUpdate` boolean NOT NULL DEFAULT true,
	`enableBonusNotification` boolean NOT NULL DEFAULT true,
	`enableApprovalRequest` boolean NOT NULL DEFAULT true,
	`enableSystemAlert` boolean NOT NULL DEFAULT true,
	`emailEnabled` boolean NOT NULL DEFAULT true,
	`pushEnabled` boolean NOT NULL DEFAULT false,
	`dailyDigest` boolean NOT NULL DEFAULT false,
	`weeklyDigest` boolean NOT NULL DEFAULT false,
	`preferredTimeStart` varchar(5) DEFAULT '08:00',
	`preferredTimeEnd` varchar(5) DEFAULT '18:00',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `userNotificationSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `userNotificationSettings_userId_unique` UNIQUE(`userId`)
);
