CREATE TABLE `bonusApprovals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cycleId` int NOT NULL,
	`employeeId` int NOT NULL,
	`workflowId` int NOT NULL,
	`eligibleAmount` decimal(10,2) NOT NULL,
	`extraBonusPercentage` decimal(5,2) DEFAULT '0',
	`finalAmount` decimal(10,2) NOT NULL,
	`currentLevel` int NOT NULL DEFAULT 1,
	`status` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
	`level1Status` enum('pending','approved','rejected') DEFAULT 'pending',
	`level1ApproverId` int,
	`level1ApprovedAt` timestamp,
	`level1Comments` text,
	`level2Status` enum('pending','approved','rejected') DEFAULT 'pending',
	`level2ApproverId` int,
	`level2ApprovedAt` timestamp,
	`level2Comments` text,
	`level3Status` enum('pending','approved','rejected') DEFAULT 'pending',
	`level3ApproverId` int,
	`level3ApprovedAt` timestamp,
	`level3Comments` text,
	`level4Status` enum('pending','approved','rejected') DEFAULT 'pending',
	`level4ApproverId` int,
	`level4ApprovedAt` timestamp,
	`level4Comments` text,
	`level5Status` enum('pending','approved','rejected') DEFAULT 'pending',
	`level5ApproverId` int,
	`level5ApprovedAt` timestamp,
	`level5Comments` text,
	`signedPdfUrl` varchar(500),
	`sentToFinanceAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bonusApprovals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bonusConfigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`positionId` int NOT NULL,
	`positionName` varchar(255) NOT NULL,
	`baseSalaryMultiplier` decimal(5,2) NOT NULL DEFAULT '0',
	`extraBonusPercentage` decimal(5,2) NOT NULL DEFAULT '0',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bonusConfigs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bonusWorkflows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`approver1Id` int,
	`approver1Role` varchar(100),
	`approver2Id` int,
	`approver2Role` varchar(100),
	`approver3Id` int,
	`approver3Role` varchar(100),
	`approver4Id` int,
	`approver4Role` varchar(100),
	`approver5Id` int,
	`approver5Role` varchar(100),
	`requireAllApprovals` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bonusWorkflows_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `goalEvidences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`goalId` int NOT NULL,
	`description` text NOT NULL,
	`attachmentUrl` varchar(500),
	`attachmentName` varchar(255),
	`attachmentType` varchar(100),
	`attachmentSize` int,
	`uploadedBy` int NOT NULL,
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	`isVerified` boolean NOT NULL DEFAULT false,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	CONSTRAINT `goalEvidences_id` PRIMARY KEY(`id`)
);
