CREATE TABLE `managerChangeHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(255),
	`employeeCode` varchar(50),
	`oldManagerId` int,
	`oldManagerName` varchar(255),
	`newManagerId` int,
	`newManagerName` varchar(255),
	`reason` text,
	`changeType` enum('promocao','transferencia','reorganizacao','desligamento_gestor','ajuste_hierarquico','outro') NOT NULL DEFAULT 'ajuste_hierarquico',
	`departmentId` int,
	`departmentName` varchar(255),
	`positionId` int,
	`positionTitle` varchar(255),
	`changedBy` int NOT NULL,
	`changedByName` varchar(255),
	`changedByRole` varchar(50),
	`requiresApproval` boolean NOT NULL DEFAULT false,
	`approvalStatus` enum('pendente','aprovado','rejeitado') DEFAULT 'aprovado',
	`approvedBy` int,
	`approvedByName` varchar(255),
	`approvedAt` datetime,
	`approvalNotes` text,
	`effectiveDate` datetime NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `managerChangeHistory_id` PRIMARY KEY(`id`)
);
