CREATE TABLE `autoGeneratedGoals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`gapAnalysisId` int NOT NULL,
	`templateId` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`specific` text,
	`measurable` text,
	`achievable` text,
	`relevant` text,
	`timeBound` text,
	`suggestedStartDate` datetime NOT NULL,
	`suggestedEndDate` datetime NOT NULL,
	`suggestedActions` json,
	`suggestedResources` json,
	`successCriteria` json,
	`targetScore` int,
	`suggestedOwnerId` int,
	`suggestedMentorId` int,
	`status` enum('pendente','aprovada','rejeitada','modificada') NOT NULL DEFAULT 'pendente',
	`approvedBy` int,
	`approvedAt` datetime,
	`rejectionReason` text,
	`pdiPlanId` int,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autoGeneratedGoals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consolidatedMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metricType` enum('overall_completion_rate','average_performance','department_performance','competency_gap','pdi_progress','assessment_distribution') NOT NULL,
	`departmentId` int,
	`positionId` int,
	`periodStart` datetime NOT NULL,
	`periodEnd` datetime NOT NULL,
	`metricValue` int NOT NULL,
	`metricData` json,
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `consolidatedMetrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `departmentAnalytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`departmentId` int NOT NULL,
	`periodStart` datetime NOT NULL,
	`periodEnd` datetime NOT NULL,
	`totalEmployees` int NOT NULL DEFAULT 0,
	`completedAssessments` int NOT NULL DEFAULT 0,
	`completionRate` int NOT NULL DEFAULT 0,
	`averagePerformanceScore` int,
	`averageCompetencyScore` int,
	`averagePirScore` int,
	`criticalGapsCount` int NOT NULL DEFAULT 0,
	`activePdisCount` int NOT NULL DEFAULT 0,
	`pdiCompletionRate` int NOT NULL DEFAULT 0,
	`competencyBreakdown` json,
	`topGaps` json,
	`topPerformers` json,
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `departmentAnalytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gapAnalysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`competencyId` int NOT NULL,
	`sourceType` enum('avaliacao_competencias','avaliacao_desempenho','pir','feedback_360') NOT NULL,
	`sourceId` int NOT NULL,
	`currentScore` int NOT NULL,
	`targetScore` int NOT NULL,
	`gapSize` int NOT NULL,
	`gapLevel` enum('critico','alto','medio','baixo') NOT NULL,
	`priority` enum('baixa','media','alta','critica') NOT NULL,
	`impactOnPerformance` int,
	`developmentDifficulty` enum('facil','medio','dificil'),
	`context` text,
	`relatedGaps` json,
	`status` enum('identificado','em_desenvolvimento','resolvido','ignorado') NOT NULL DEFAULT 'identificado',
	`resolvedAt` datetime,
	`identifiedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gapAnalysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `goalGenerationHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`triggerType` enum('avaliacao_concluida','gap_identificado','solicitacao_manual','revisao_periodica') NOT NULL,
	`triggerId` int,
	`gapsAnalyzed` int NOT NULL DEFAULT 0,
	`goalsGenerated` int NOT NULL DEFAULT 0,
	`goalsApproved` int NOT NULL DEFAULT 0,
	`goalsRejected` int NOT NULL DEFAULT 0,
	`analysisData` json,
	`generatedGoalIds` json,
	`generatedAt` timestamp NOT NULL DEFAULT (now()),
	`generatedBy` int,
	CONSTRAINT `goalGenerationHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `goalTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competencyId` int NOT NULL,
	`gapLevel` enum('critico','alto','medio','baixo') NOT NULL,
	`titleTemplate` varchar(255) NOT NULL,
	`descriptionTemplate` text,
	`suggestedDurationDays` int NOT NULL,
	`suggestedActions` json,
	`suggestedResources` json,
	`successCriteria` json,
	`targetScore` int,
	`category` varchar(100),
	`priority` enum('baixa','media','alta','critica') NOT NULL DEFAULT 'media',
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `goalTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trendAnalytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trendType` enum('performance_evolution','competency_growth','gap_reduction','pdi_effectiveness','assessment_participation') NOT NULL,
	`departmentId` int,
	`employeeId` int,
	`competencyId` int,
	`timeSeriesData` json NOT NULL,
	`trend` enum('increasing','stable','decreasing'),
	`trendStrength` int,
	`projectedValue` int,
	`periodStart` datetime NOT NULL,
	`periodEnd` datetime NOT NULL,
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `trendAnalytics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `pirIntegrityQuestions` ADD `videoUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `pirIntegrityQuestions` ADD `videoThumbnailUrl` varchar(512);--> statement-breakpoint
ALTER TABLE `pirIntegrityQuestions` ADD `videoDuration` int;--> statement-breakpoint
ALTER TABLE `pirIntegrityQuestions` ADD `requiresVideoWatch` boolean DEFAULT false NOT NULL;