CREATE TABLE `marketBenchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sector` varchar(100) NOT NULL,
	`position` varchar(100) NOT NULL,
	`region` varchar(100) NOT NULL DEFAULT 'Brasil',
	`avgPerformanceScore` int,
	`avgEngagementScore` int,
	`avgTurnoverRate` int,
	`avgTenureYears` int,
	`avgSalary` int,
	`medianSalary` int,
	`avgDiscD` int,
	`avgDiscI` int,
	`avgDiscS` int,
	`avgDiscC` int,
	`avgOpenness` int,
	`avgConscientiousness` int,
	`avgExtraversion` int,
	`avgAgreeableness` int,
	`avgNeuroticism` int,
	`sampleSize` int,
	`dataSource` varchar(255),
	`year` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `marketBenchmarks_id` PRIMARY KEY(`id`)
);
