CREATE TABLE `importHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileSize` int NOT NULL,
	`fileHash` varchar(64),
	`importType` enum('employees','hierarchy','departments','positions','job_descriptions','full') NOT NULL,
	`source` enum('manual','api','scheduled') NOT NULL DEFAULT 'manual',
	`status` enum('pending','processing','completed','completed_with_errors','failed','cancelled','reverted') NOT NULL DEFAULT 'pending',
	`totalRecords` int DEFAULT 0,
	`successfulRecords` int DEFAULT 0,
	`failedRecords` int DEFAULT 0,
	`skippedRecords` int DEFAULT 0,
	`updatedRecords` int DEFAULT 0,
	`createdRecords` int DEFAULT 0,
	`deletedRecords` int DEFAULT 0,
	`summary` json,
	`backupData` json,
	`canRevert` boolean NOT NULL DEFAULT true,
	`revertedAt` timestamp,
	`revertedBy` int,
	`importedBy` int NOT NULL,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`processingTimeMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `importHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `importLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`importHistoryId` int NOT NULL,
	`logType` enum('error','warning','info','success') NOT NULL,
	`severity` enum('critical','high','medium','low') NOT NULL DEFAULT 'medium',
	`rowNumber` int,
	`columnName` varchar(100),
	`recordId` varchar(100),
	`errorCode` varchar(50),
	`message` text NOT NULL,
	`details` json,
	`stackTrace` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `importLogs_id` PRIMARY KEY(`id`)
);
