CREATE TABLE `bonusCalculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`policyId` int NOT NULL,
	`employeeId` int NOT NULL,
	`baseSalary` decimal(10,2) NOT NULL,
	`appliedMultiplier` decimal(5,2) NOT NULL,
	`bonusAmount` decimal(10,2) NOT NULL,
	`performanceScore` int,
	`goalCompletionRate` int,
	`adjustmentReason` text,
	`status` enum('calculado','aprovado','pago','cancelado') NOT NULL DEFAULT 'calculado',
	`approvedBy` int,
	`approvedAt` datetime,
	`paidAt` datetime,
	`calculatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`referenceMonth` varchar(7) NOT NULL,
	CONSTRAINT `bonusCalculations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bonusPolicies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(200) NOT NULL,
	`description` text,
	`positionId` int,
	`departmentId` int,
	`salaryMultiplier` decimal(5,2) NOT NULL,
	`minMultiplier` decimal(5,2) DEFAULT '0.5',
	`maxMultiplier` decimal(5,2) DEFAULT '2.0',
	`minPerformanceRating` enum('abaixo_expectativas','atende_expectativas','supera_expectativas','excepcional') DEFAULT 'atende_expectativas',
	`minTenureMonths` int DEFAULT 6,
	`requiresGoalCompletion` boolean DEFAULT true,
	`minGoalCompletionRate` int DEFAULT 70,
	`validFrom` datetime NOT NULL,
	`validUntil` datetime,
	`active` boolean NOT NULL DEFAULT true,
	`approvalStatus` enum('pendente','aprovado','rejeitado') NOT NULL DEFAULT 'pendente',
	`approvedBy` int,
	`approvedAt` datetime,
	`createdBy` int NOT NULL,
	`createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `bonusPolicies_id` PRIMARY KEY(`id`)
);
