DROP TABLE `activityLogs`;--> statement-breakpoint
DROP TABLE `adminUsers`;--> statement-breakpoint
DROP TABLE `auditLogs`;--> statement-breakpoint
DROP TABLE `badges`;--> statement-breakpoint
DROP TABLE `bonusApprovalComments`;--> statement-breakpoint
DROP TABLE `bonusApprovals`;--> statement-breakpoint
DROP TABLE `bonusAuditLogs`;--> statement-breakpoint
DROP TABLE `bonusCalculations`;--> statement-breakpoint
DROP TABLE `bonusConfigs`;--> statement-breakpoint
DROP TABLE `bonusPolicies`;--> statement-breakpoint
DROP TABLE `bonusWorkflows`;--> statement-breakpoint
DROP TABLE `calibrationApprovals`;--> statement-breakpoint
DROP TABLE `calibrationComparisons`;--> statement-breakpoint
DROP TABLE `calibrationMessages`;--> statement-breakpoint
DROP TABLE `calibrationMovements`;--> statement-breakpoint
DROP TABLE `calibrationParticipants`;--> statement-breakpoint
DROP TABLE `calibrationReviews`;--> statement-breakpoint
DROP TABLE `calibrationSessions`;--> statement-breakpoint
DROP TABLE `calibrationVotes`;--> statement-breakpoint
DROP TABLE `calibrationWorkflows`;--> statement-breakpoint
DROP TABLE `competencies`;--> statement-breakpoint
DROP TABLE `competencyLevels`;--> statement-breakpoint
DROP TABLE `costCenters`;--> statement-breakpoint
DROP TABLE `customReports`;--> statement-breakpoint
DROP TABLE `departments`;--> statement-breakpoint
DROP TABLE `developmentActions`;--> statement-breakpoint
DROP TABLE `emailMetrics`;--> statement-breakpoint
DROP TABLE `employeeActivities`;--> statement-breakpoint
DROP TABLE `employeeBadges`;--> statement-breakpoint
DROP TABLE `employeeCompetencies`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `evaluationCycles`;--> statement-breakpoint
DROP TABLE `evaluationQuestions`;--> statement-breakpoint
DROP TABLE `evaluationResponses`;--> statement-breakpoint
DROP TABLE `evaluationTemplates`;--> statement-breakpoint
DROP TABLE `feedbacks`;--> statement-breakpoint
DROP TABLE `goalApprovals`;--> statement-breakpoint
DROP TABLE `goalComments`;--> statement-breakpoint
DROP TABLE `goalEvidences`;--> statement-breakpoint
DROP TABLE `goalMilestones`;--> statement-breakpoint
DROP TABLE `goalUpdates`;--> statement-breakpoint
DROP TABLE `goals`;--> statement-breakpoint
DROP TABLE `jobCompetencies`;--> statement-breakpoint
DROP TABLE `jobDescriptionApprovals`;--> statement-breakpoint
DROP TABLE `jobDescriptions`;--> statement-breakpoint
DROP TABLE `jobKnowledge`;--> statement-breakpoint
DROP TABLE `jobResponsibilities`;--> statement-breakpoint
DROP TABLE `marketBenchmarks`;--> statement-breakpoint
DROP TABLE `nineBoxPositions`;--> statement-breakpoint
DROP TABLE `notificationTemplates`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `passwordChangeHistory`;--> statement-breakpoint
DROP TABLE `passwordResetTokens`;--> statement-breakpoint
DROP TABLE `pdiActions`;--> statement-breakpoint
DROP TABLE `pdiCompetencyGaps`;--> statement-breakpoint
DROP TABLE `pdiGovernanceReviews`;--> statement-breakpoint
DROP TABLE `pdiIntelligentDetails`;--> statement-breakpoint
DROP TABLE `pdiItems`;--> statement-breakpoint
DROP TABLE `pdiPlans`;--> statement-breakpoint
DROP TABLE `pdiProgress`;--> statement-breakpoint
DROP TABLE `pdiReviews`;--> statement-breakpoint
DROP TABLE `pdiRisks`;--> statement-breakpoint
DROP TABLE `performanceEvaluationApprovals`;--> statement-breakpoint
DROP TABLE `performanceEvaluationCycles`;--> statement-breakpoint
DROP TABLE `performanceEvaluationEvidences`;--> statement-breakpoint
DROP TABLE `performanceEvaluationParticipants`;--> statement-breakpoint
DROP TABLE `performanceEvaluations`;--> statement-breakpoint
DROP TABLE `positionCompetencies`;--> statement-breakpoint
DROP TABLE `positions`;--> statement-breakpoint
DROP TABLE `psychometricTests`;--> statement-breakpoint
DROP TABLE `pulseSurveyEmailLogs`;--> statement-breakpoint
DROP TABLE `pulseSurveyResponses`;--> statement-breakpoint
DROP TABLE `pulseSurveys`;--> statement-breakpoint
DROP TABLE `pushNotificationLogs`;--> statement-breakpoint
DROP TABLE `pushSubscriptions`;--> statement-breakpoint
DROP TABLE `reportAnalytics`;--> statement-breakpoint
DROP TABLE `reportExecutionLogs`;--> statement-breakpoint
DROP TABLE `scheduledReports`;--> statement-breakpoint
DROP TABLE `smartGoals`;--> statement-breakpoint
DROP TABLE `smtp_config`;--> statement-breakpoint
DROP TABLE `successionCandidates`;--> statement-breakpoint
DROP TABLE `successionHistory`;--> statement-breakpoint
DROP TABLE `successionPlans`;--> statement-breakpoint
DROP TABLE `systemSettings`;--> statement-breakpoint
DROP TABLE `templateQuestions`;--> statement-breakpoint
DROP TABLE `testQuestions`;--> statement-breakpoint
DROP TABLE `workflowInstances`;--> statement-breakpoint
DROP TABLE `workflowStepApprovals`;--> statement-breakpoint
DROP TABLE `workflows`;--> statement-breakpoint
DROP TABLE `alerts`;--> statement-breakpoint
DROP TABLE `timeClockRecords`;--> statement-breakpoint
DROP TABLE `timeDiscrepancies`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `faceDescriptor`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `facePhotoUrl`;--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `faceRegisteredAt`;