import { useState } from "react";
import { trpc } from "@/lib/trpc";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { 
  Target, 
  TrendingDown, 
  Sparkles, 
  CheckCircle2, 
  XCircle, 
  Edit,
  Loader2,
  AlertCircle,
  Calendar,
  User
} from "lucide-react";
import { safeMap } from "@/lib/arrayHelpers";
import { toast } from "sonner";

/**
 * Sistema de Metas Automáticas - Geração baseada em gaps
 */
export default function MetasAutomaticas() {
  const [selectedEmployee, setSelectedEmployee] = useState<number | null>(null);
  const [showApprovalDialog, setShowApprovalDialog] = useState(false);
  const [selectedGoal, setSelectedGoal] = useState<any>(null);
  const [modifications, setModifications] = useState({
    title: "",
    description: "",
    suggestedStartDate: "",
    suggestedEndDate: "",
  });

  // Queries
  const { data: employeesData } = trpc.employees.list.useQuery({ active: true });
  
  const { data: gapsData, refetch: refetchGaps } = trpc.autoGoals.listGaps.useQuery(
    { employeeId: selectedEmployee!, status: "identificado" },
    { enabled: !!selectedEmployee }
  );

  const { data: goalsData, refetch: refetchGoals } = trpc.autoGoals.listAutoGeneratedGoals.useQuery(
    { employeeId: selectedEmployee! },
    { enabled: !!selectedEmployee }
  );

  // Mutations
  const generateGoals = trpc.autoGoals.generateGoals.useMutation({
    onSuccess: (data) => {
      toast.success(`${data.goalsGenerated} metas geradas com sucesso!`);
      refetchGaps();
      refetchGoals();
    },
    onError: () => toast.error("Erro ao gerar metas"),
  });

  const approveGoal = trpc.autoGoals.approveGoal.useMutation({
    onSuccess: () => {
      toast.success("Meta aprovada e PDI criado!");
      refetchGoals();
      setShowApprovalDialog(false);
    },
    onError: () => toast.error("Erro ao aprovar meta"),
  });

  const rejectGoal = trpc.autoGoals.rejectGoal.useMutation({
    onSuccess: () => {
      toast.success("Meta rejeitada");
      refetchGoals();
      setShowApprovalDialog(false);
    },
    onError: () => toast.error("Erro ao rejeitar meta"),
  });

  const handleGenerateGoals = () => {
    if (!selectedEmployee) {
      toast.error("Selecione um colaborador");
      return;
    }
    generateGoals.mutate({ employeeId: selectedEmployee });
  };

  const openApprovalDialog = (goal: any) => {
    setSelectedGoal(goal);
    setModifications({
      title: goal.goal.title,
      description: goal.goal.description || "",
      suggestedStartDate: new Date(goal.goal.suggestedStartDate).toISOString().split('T')[0],
      suggestedEndDate: new Date(goal.goal.suggestedEndDate).toISOString().split('T')[0],
    });
    setShowApprovalDialog(true);
  };

  const handleApprove = () => {
    if (!selectedGoal) return;
    
    const hasModifications = 
      modifications.title !== selectedGoal.goal.title ||
      modifications.description !== selectedGoal.goal.description ||
      modifications.suggestedStartDate !== new Date(selectedGoal.goal.suggestedStartDate).toISOString().split('T')[0] ||
      modifications.suggestedEndDate !== new Date(selectedGoal.goal.suggestedEndDate).toISOString().split('T')[0];

    approveGoal.mutate({
      goalId: selectedGoal.goal.id,
      modifications: hasModifications ? {
        title: modifications.title,
        description: modifications.description,
        suggestedStartDate: new Date(modifications.suggestedStartDate),
        suggestedEndDate: new Date(modifications.suggestedEndDate),
      } : undefined,
    });
  };

  const handleReject = () => {
    if (!selectedGoal) return;
    const reason = prompt("Motivo da rejeição:");
    if (reason) {
      rejectGoal.mutate({ goalId: selectedGoal.goal.id, reason });
    }
  };

  const gaps = gapsData?.gaps || [];
  const goals = goalsData?.goals || [];
  const pendingGoals = goals.filter(g => g.goal.status === "pendente");
  const approvedGoals = goals.filter(g => g.goal.status === "aprovada" || g.goal.status === "modificada");

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold flex items-center gap-2">
              <Sparkles className="h-8 w-8 text-purple-600" />
              Metas Automáticas
            </h1>
            <p className="text-gray-600 mt-1">Geração inteligente de metas baseada em gaps identificados</p>
          </div>
        </div>

        {/* Seleção de Colaborador */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="flex-1">
                <Label>Selecione um Colaborador</Label>
                <select
                  className="w-full mt-2 px-3 py-2 border rounded-md"
                  value={selectedEmployee || ""}
                  onChange={(e) => setSelectedEmployee(e.target.value ? parseInt(e.target.value) : null)}
                >
                  <option value="">-- Selecione --</option>
                  {safeMap(employeesData?.employees, emp => (
                    <option key={emp.id} value={emp.id}>{emp.name}</option>
                  ))}
                </select>
              </div>
              <Button 
                onClick={handleGenerateGoals}
                disabled={!selectedEmployee || generateGoals.isPending}
                className="mt-8"
              >
                {generateGoals.isPending ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <Sparkles className="h-4 w-4 mr-2" />
                )}
                Gerar Metas Automáticas
              </Button>
            </div>
          </CardContent>
        </Card>

        {selectedEmployee && (
          <>
            {/* Gaps Identificados */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingDown className="h-5 w-5 text-orange-600" />
                  Gaps Identificados ({gaps.length})
                </CardTitle>
              </CardHeader>
              <CardContent>
                {gaps.length === 0 ? (
                  <p className="text-gray-500 text-center py-8">Nenhum gap identificado</p>
                ) : (
                  <div className="space-y-3">
                    {safeMap(gaps, ({ gap, competency }) => (
                      <div key={gap.id} className="border rounded-lg p-4">
                        <div className="flex items-center justify-between mb-2">
                          <h3 className="font-semibold">{competency?.name}</h3>
                          <div className="flex items-center gap-2">
                            <Badge variant={
                              gap.gapLevel === "critico" ? "destructive" :
                              gap.gapLevel === "alto" ? "secondary" :
                              "outline"
                            }>
                              {gap.gapLevel}
                            </Badge>
                            <Badge variant="outline">{gap.priority}</Badge>
                          </div>
                        </div>
                        <div className="grid grid-cols-3 gap-4 text-sm">
                          <div>
                            <p className="text-gray-600">Score Atual</p>
                            <p className="font-semibold text-lg">{gap.currentScore}</p>
                          </div>
                          <div>
                            <p className="text-gray-600">Meta</p>
                            <p className="font-semibold text-lg">{gap.targetScore}</p>
                          </div>
                          <div>
                            <p className="text-gray-600">Gap</p>
                            <p className="font-semibold text-lg text-red-600">{gap.gapSize}</p>
                          </div>
                        </div>
                        {gap.context && (
                          <p className="text-sm text-gray-600 mt-2">{gap.context}</p>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Metas Pendentes de Aprovação */}
            {pendingGoals.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <AlertCircle className="h-5 w-5 text-yellow-600" />
                    Metas Pendentes de Aprovação ({pendingGoals.length})
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {safeMap(pendingGoals, goalData => (
                      <div key={goalData.goal.id} className="border rounded-lg p-4">
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex-1">
                            <h3 className="font-semibold text-lg">{goalData.goal.title}</h3>
                            <p className="text-sm text-gray-600 mt-1">{goalData.goal.description}</p>
                          </div>
                          <Badge className="bg-purple-100 text-purple-800">
                            Auto-gerada
                          </Badge>
                        </div>

                        {/* Critérios SMART */}
                        <div className="grid grid-cols-2 gap-3 mb-3 text-sm">
                          <div className="bg-gray-50 p-2 rounded">
                            <p className="font-medium text-gray-700">Específico</p>
                            <p className="text-gray-600">{goalData.goal.specific}</p>
                          </div>
                          <div className="bg-gray-50 p-2 rounded">
                            <p className="font-medium text-gray-700">Mensurável</p>
                            <p className="text-gray-600">{goalData.goal.measurable}</p>
                          </div>
                          <div className="bg-gray-50 p-2 rounded">
                            <p className="font-medium text-gray-700">Alcançável</p>
                            <p className="text-gray-600">{goalData.goal.achievable}</p>
                          </div>
                          <div className="bg-gray-50 p-2 rounded">
                            <p className="font-medium text-gray-700">Temporal</p>
                            <p className="text-gray-600">{goalData.goal.timeBound}</p>
                          </div>
                        </div>

                        <div className="flex items-center gap-4 text-sm text-gray-600 mb-3">
                          <div className="flex items-center gap-1">
                            <Calendar className="h-4 w-4" />
                            {new Date(goalData.goal.suggestedStartDate).toLocaleDateString()} - {new Date(goalData.goal.suggestedEndDate).toLocaleDateString()}
                          </div>
                          <div className="flex items-center gap-1">
                            <Target className="h-4 w-4" />
                            Meta: {goalData.goal.targetScore}
                          </div>
                        </div>

                        <div className="flex gap-2">
                          <Button 
                            onClick={() => openApprovalDialog(goalData)}
                            className="flex-1"
                          >
                            <CheckCircle2 className="h-4 w-4 mr-2" />
                            Aprovar e Criar PDI
                          </Button>
                          <Button 
                            variant="outline"
                            onClick={() => openApprovalDialog(goalData)}
                          >
                            <Edit className="h-4 w-4 mr-2" />
                            Editar
                          </Button>
                          <Button 
                            variant="destructive"
                            onClick={() => {
                              setSelectedGoal(goalData);
                              handleReject();
                            }}
                          >
                            <XCircle className="h-4 w-4 mr-2" />
                            Rejeitar
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Metas Aprovadas */}
            {approvedGoals.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CheckCircle2 className="h-5 w-5 text-green-600" />
                    Metas Aprovadas ({approvedGoals.length})
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {safeMap(approvedGoals, goalData => (
                      <div key={goalData.goal.id} className="border rounded-lg p-4 bg-green-50">
                        <div className="flex items-center justify-between">
                          <div className="flex-1">
                            <h3 className="font-semibold">{goalData.goal.title}</h3>
                            <p className="text-sm text-gray-600 mt-1">{goalData.competency?.name}</p>
                          </div>
                          <Badge className="bg-green-100 text-green-800">
                            {goalData.goal.status === "modificada" ? "Modificada" : "Aprovada"}
                          </Badge>
                        </div>
                        {goalData.goal.pdiPlanId && (
                          <p className="text-sm text-gray-600 mt-2">
                            PDI #{goalData.goal.pdiPlanId} criado
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </>
        )}

        {/* Dialog de Aprovação/Edição */}
        <Dialog open={showApprovalDialog} onOpenChange={setShowApprovalDialog}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Revisar e Aprovar Meta</DialogTitle>
            </DialogHeader>
            {selectedGoal && (
              <div className="space-y-4">
                <div>
                  <Label>Título da Meta</Label>
                  <Input
                    value={modifications.title}
                    onChange={(e) => setModifications(p => ({ ...p, title: e.target.value }))}
                  />
                </div>
                <div>
                  <Label>Descrição</Label>
                  <Textarea
                    value={modifications.description}
                    onChange={(e) => setModifications(p => ({ ...p, description: e.target.value }))}
                    rows={3}
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label>Data de Início</Label>
                    <Input
                      type="date"
                      value={modifications.suggestedStartDate}
                      onChange={(e) => setModifications(p => ({ ...p, suggestedStartDate: e.target.value }))}
                    />
                  </div>
                  <div>
                    <Label>Data de Término</Label>
                    <Input
                      type="date"
                      value={modifications.suggestedEndDate}
                      onChange={(e) => setModifications(p => ({ ...p, suggestedEndDate: e.target.value }))}
                    />
                  </div>
                </div>
                <div className="flex gap-2 pt-4">
                  <Button 
                    onClick={handleApprove}
                    disabled={approveGoal.isPending}
                    className="flex-1"
                  >
                    {approveGoal.isPending ? (
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    ) : (
                      <CheckCircle2 className="h-4 w-4 mr-2" />
                    )}
                    Aprovar e Criar PDI
                  </Button>
                  <Button 
                    variant="outline"
                    onClick={() => setShowApprovalDialog(false)}
                  >
                    Cancelar
                  </Button>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </DashboardLayout>
  );
}
